### ISSUE TITLE
The issue while creating the todo.

### ISSUE THREAD

**Issue by shivamnarkar47** [10kumaranurag01/todo-done#1]
### Issue
- It first closes dialog and then specify that the fields must not be empty.

![image](https://github.com/user-attachments/assets/d3791c9d-3133-4fb1-8b78-26b49368bf63)

**Comment by 10kumaranurag01** [comment]
Want to work on this? @shivamnarkar47

**Comment by Abhiraj-Sardar** [comment]
@shivamnarkar47  I would like to work on this...

**Comment by 10kumaranurag01** [comment]
Fork the repo and add an new branch and make a PR. Thank you @Abhiraj-Sardar

**Comment by Abhiraj-Sardar** [comment]
Hi @10kumaranurag01 

I Just Updated AddEditTodoDialog.js, to solve the [Issue #1](https://github.com/10kumaranurag01/todo-done/issues/1).
There was a Rendering related issue were the same component is getting re-rendered again when you click on other component. But the issue is solved now.


Before Updatation:
![image](https://github.com/user-attachments/assets/b4ab94b0-93a6-4056-814d-cf3135d9f14c)

After Updatation:

https://github.com/user-attachments/assets/59f797eb-b6d6-4a4b-89c6-4c47ec069cd9


You have to authorize this update in vercel. I think, as I didn't have vercel account...
![issue](https://github.com/user-attachments/assets/c6a834c8-3dfc-49d2-b131-7d77dd22e01b)
